// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchedulePicker.Data;

namespace SchedulePicker.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200808021221_AddSeedAllCSCoursesMajors")]
    partial class AddSeedAllCSCoursesMajors
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Student");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.StudentClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.StudentLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.StudentRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.StudentToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SchedulePicker.Models.CoReq", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CorequisiteId")
                        .HasColumnType("int");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CorequisiteId");

                    b.HasIndex("CourseId");

                    b.ToTable("CoReqs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorequisiteId = 15,
                            CourseId = 4
                        },
                        new
                        {
                            Id = 2,
                            CorequisiteId = 14,
                            CourseId = 4
                        },
                        new
                        {
                            Id = 3,
                            CorequisiteId = 16,
                            CourseId = 5
                        },
                        new
                        {
                            Id = 4,
                            CorequisiteId = 5,
                            CourseId = 16
                        },
                        new
                        {
                            Id = 5,
                            CorequisiteId = 4,
                            CourseId = 15
                        });
                });

            modelBuilder.Entity("SchedulePicker.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClassLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseType")
                        .HasColumnType("int");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Prefix")
                        .HasColumnType("nvarchar(4)")
                        .HasMaxLength(4);

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            ClassLevel = "UnderGraduate",
                            CourseType = 0,
                            Credits = 3,
                            Description = "This course presents an integrated approach to writing, reading, and critical thinking by developing the grammatical, logical, and rhetorical skills necessary for university writing.",
                            Name = "Rhetoric",
                            Number = 1302,
                            Prefix = "RHET"
                        },
                        new
                        {
                            CourseId = 2,
                            ClassLevel = "UnderGraduate",
                            CourseType = 2,
                            Credits = 3,
                            Description = "Expands students' professional and team communication skills and strategies in technical contexts. Integrates writing, speaking and group communication by developing and presenting technical information to different audiences. Written assignments focus on creating professional technical documents, such as proposals, memos, abstracts, reports and letters. Presentation assignments emphasize planning, preparing and delivering dynamic, informative and persuasive presentations. Attendance at first class mandatory.",
                            Name = "Professional and Technical Communication",
                            Number = 3390,
                            Prefix = "ECS"
                        },
                        new
                        {
                            CourseId = 3,
                            ClassLevel = "UnderGraduate",
                            CourseType = 1,
                            Credits = 4,
                            Description = "Functions, limits, continuity, differentiation; integration of function of one variable; logarithmic, exponential, and inverse trigonometric functions; techniques of integration, and applications. Three lecture hours and two discussion hours a week; problem section required with MATH 2417, and will also be registered for exam section. Not all MATH/STAT courses may be counted toward various degree plans. Please consult your degree plan to determine the appropriate MATH/STAT course requirements. ",
                            Name = "Calculus I",
                            Number = 3417,
                            Prefix = "MATH"
                        },
                        new
                        {
                            CourseId = 4,
                            ClassLevel = "UnderGraduate",
                            CourseType = 1,
                            Credits = 3,
                            Description = "Calculus based. Basic physics including a study of space and time, kinematics, forces, energy and momentum, conservation laws, rotational motion, torques, and harmonic oscillation. Two lectures per week. Students will also be registered for an exam section.",
                            Name = "Mechanics",
                            Number = 2325,
                            Prefix = "PHYS"
                        },
                        new
                        {
                            CourseId = 5,
                            ClassLevel = "UnderGraduate",
                            CourseType = 1,
                            Credits = 3,
                            Description = "Topics include electrostatics and electromagnetics, electric field and potential, electric currents, magnetic fields, laws of Coulomb, Ampere, and Faraday, Maxwell's theory of wave propagation. Two lectures per week. Students will also be registered for an exam section.",
                            Name = "Electromagnetism and Waves",
                            Number = 2326,
                            Prefix = "PHYS"
                        },
                        new
                        {
                            CourseId = 6,
                            ClassLevel = "UnderGraduate",
                            CourseType = 0,
                            Credits = 3,
                            Description = "",
                            Name = "Language, Philosphy and Culture",
                            Number = 0,
                            Prefix = ""
                        },
                        new
                        {
                            CourseId = 7,
                            ClassLevel = "UnderGraduate",
                            CourseType = 0,
                            Credits = 3,
                            Description = "",
                            Name = "Creative Arts I",
                            Number = 0,
                            Prefix = ""
                        },
                        new
                        {
                            CourseId = 8,
                            ClassLevel = "UnderGraduate",
                            CourseType = 0,
                            Credits = 3,
                            Description = "",
                            Name = "Creative Arts II",
                            Number = 0,
                            Prefix = ""
                        },
                        new
                        {
                            CourseId = 9,
                            ClassLevel = "UnderGraduate",
                            CourseType = 0,
                            Credits = 3,
                            Description = "",
                            Name = "American History I",
                            Number = 0,
                            Prefix = ""
                        },
                        new
                        {
                            CourseId = 10,
                            ClassLevel = "UnderGraduate",
                            CourseType = 0,
                            Credits = 3,
                            Description = "",
                            Name = "American History II",
                            Number = 0,
                            Prefix = ""
                        },
                        new
                        {
                            CourseId = 11,
                            ClassLevel = "UnderGraduate",
                            CourseType = 0,
                            Credits = 3,
                            Description = "Survey of American national government, politics, and constitutional development. ",
                            Name = "American National Government",
                            Number = 2305,
                            Prefix = "GOVT"
                        },
                        new
                        {
                            CourseId = 12,
                            ClassLevel = "UnderGraduate",
                            CourseType = 0,
                            Credits = 3,
                            Description = "Survey of state and local government and politics with special reference to the constitution and politics of Texas.",
                            Name = "State and Local Government",
                            Number = 2306,
                            Prefix = "GOVT"
                        },
                        new
                        {
                            CourseId = 13,
                            ClassLevel = "UnderGraduate",
                            CourseType = 0,
                            Credits = 3,
                            Description = "This course exposes students to major theoretical approaches and professional codes of ethics and how they may be applied to explore a range of important social issues in the information age. Issues of professional ethics, computer crime and privacy, intellectual property, the balance between the acceptability of risk and constraints such as cost, scheduling, safety and quality, the role of globalization and various important constitutional issues are explored by drawing upon case studies. Prerequisite: Completion of an 030 core course.",
                            Name = "Social Issues and Ethics in Science and Technology",
                            Number = 2361,
                            Prefix = "ECS"
                        },
                        new
                        {
                            CourseId = 14,
                            ClassLevel = "UnderGraduate",
                            CourseType = 0,
                            Credits = 4,
                            Description = "Improper integrals, sequences, infinite series, power series, parametric equations and polar coordinates, vectors, vector valued functions, functions of several variables, partial derivatives and applications, and multiple integration. Three lecture hours and two discussion hours a week; problem section required with MATH 2419, and will also be registered for exam section. ",
                            Name = "Calculus II",
                            Number = 2419,
                            Prefix = "MATH"
                        },
                        new
                        {
                            CourseId = 15,
                            ClassLevel = "UnderGraduate",
                            CourseType = 1,
                            Credits = 1,
                            Description = "Laboratory course to accompany any Physics I or Mechanics course. Experiments investigate basic measurements and statistics including error, mean, standard deviation and error propagation; one dimensional and two dimensional motion; Newton's laws; conservation laws of energy and momentum; rotational motion; and oscillations.",
                            Name = "Physics Lab I",
                            Number = 2125,
                            Prefix = "PHYS"
                        },
                        new
                        {
                            CourseId = 16,
                            ClassLevel = "UnderGraduate",
                            CourseType = 1,
                            Credits = 1,
                            Description = "Laboratory course to accompany any Physics II or Electricity and Magnetism course. Experiments investigate electrostatics, electricity in simple circuits, RC circuits and magnetism. ",
                            Name = "Physics Lab II",
                            Number = 2126,
                            Prefix = "PHYS"
                        },
                        new
                        {
                            CourseId = 17,
                            ClassLevel = "UnderGraduate",
                            CourseType = 1,
                            Credits = 1,
                            Description = "Introduction to engineering and computing careers; overview of Engineering and Computer Science (ECS) curricula, connections among ECS fields and to the sciences, and other fields; basic study, problem solving, and other skills needed to succeed as an ECS major.",
                            Name = "Introduction to Engineering and Computer Science",
                            Number = 1100,
                            Prefix = "ECS"
                        },
                        new
                        {
                            CourseId = 18,
                            ClassLevel = "UnderGraduate",
                            CourseType = 1,
                            Credits = 2,
                            Description = "Introduction to the computing professions; overview of Computer Science (CS) and Software Engineering (SE) curricula, connections with Computer Engineering, other Engineering and Computer Science fields, and Arts and Technology programs; problem solving and other skills needed to succeed as a CS or SE major. Introduction to quantitative methods; team projects designed to replicate decision processes and problem solving in real-world situations; additional preparatory topics for CS and SE majors.",
                            Name = "Introduction to Computer Science and Software Engineering",
                            Number = 1200,
                            Prefix = "CS"
                        },
                        new
                        {
                            CourseId = 19,
                            ClassLevel = "UnderGraduate",
                            CourseType = 1,
                            Credits = 3,
                            Description = "Review of control structures and data types with emphasis on structured data types. Applies the object-oriented programming paradigm, focusing on the definition and use of classes along with the fundamentals of object-oriented design. Includes basic analysis of algorithms, searching and sorting techniques, and an introduction to software engineering. Programming language of choice is C/C++. Students will also be registered for an exam section.",
                            Name = "Computer Science I",
                            Number = 1337,
                            Prefix = "CS"
                        },
                        new
                        {
                            CourseId = 20,
                            ClassLevel = "UnderGraduate",
                            CourseType = 1,
                            Credits = 3,
                            Description = "Principles of counting. Boolean operations. Logic and proof methods. Recurrence relations. Sets, relations, functions. Elementary graph theory. Elementary number theory. ",
                            Name = "Discrete Mathematics for Computing I",
                            Number = 2305,
                            Prefix = "CS"
                        },
                        new
                        {
                            CourseId = 21,
                            ClassLevel = "UnderGraduate",
                            CourseType = 1,
                            Credits = 3,
                            Description = "Further applications of programming techniques, introducing the fundamental concepts of data structures and algorithms. Topics include recursion, fundamental data structures (including stacks, queues, linked lists, hash tables, trees, and graphs), and algorithmic analysis. Includes comprehensive programming projects. Programming language of choice is Java. ",
                            Name = "Computer Science II",
                            Number = 2336,
                            Prefix = "CS"
                        },
                        new
                        {
                            CourseId = 22,
                            ClassLevel = "UnderGraduate",
                            CourseType = 1,
                            Credits = 4,
                            Description = "Introduces and provides models for application of the concepts of vector algebra. Topics include finite dimensional vector spaces and their geometric significance; representing and solving systems of linear equations using multiple methods, including Gaussian elimination and matrix inversion; matrices; determinants; linear transformations; quadratic forms; eigenvalues and eigenvectors; and applications in science and engineering. Three lecture hours and two discussion hours a week; ",
                            Name = "Linear Algebra",
                            Number = 2418,
                            Prefix = "MATH"
                        },
                        new
                        {
                            CourseId = 23,
                            ClassLevel = "UnderGraduate",
                            CourseType = 1,
                            Credits = 3,
                            Description = "A science elective",
                            Name = "Science Elective",
                            Number = 0,
                            Prefix = ""
                        },
                        new
                        {
                            CourseId = 24,
                            ClassLevel = "UnderGraduate",
                            CourseType = 2,
                            Credits = 1,
                            Description = "Professional and ethical responsibilities of computer scientists and software engineers as influenced by growth in computer use and networks. Costs and benefits of computer technology. Risks and liabilities of safety-critical systems. Social implications of the Internet. Interaction between human values and technical decisions involving computing.",
                            Name = "Professional Responsibility in Computer Science and Software Engineering",
                            Number = 3162,
                            Prefix = "CS"
                        },
                        new
                        {
                            CourseId = 25,
                            ClassLevel = "UnderGraduate",
                            CourseType = 2,
                            Credits = 3,
                            Description = "Advanced counting methods; recurrence relations, divide and conquer algorithms, principle of inclusion and exclusion. Partial orders and lattices, Algorithmic complexity. Graph theory. Strings and languages. Number theory. Elements of modern algebra.",
                            Name = "Discrete Mathematics for Computing II",
                            Number = 3305,
                            Prefix = "CS"
                        },
                        new
                        {
                            CourseId = 26,
                            ClassLevel = "UnderGraduate",
                            CourseType = 2,
                            Credits = 3,
                            Description = "This course introduces the concepts of computer architecture by going through multiple levels of abstraction, and the numbering systems and their basic computations. It focuses on the instruction-set architecture of the MIPS machine, including MIPS assembly programming, translation between MIPS and C, and between MIPS and machine code. General topics include performance calculation, processor datapath, pipelining, and memory hierarchy.",
                            Name = "Computer Architecture",
                            Number = 3340,
                            Prefix = "CS"
                        },
                        new
                        {
                            CourseId = 27,
                            ClassLevel = "UnderGraduate",
                            CourseType = 2,
                            Credits = 3,
                            Description = "Axiomatic probability theory, independence, conditional probability. Discrete and continuous random variables, special distributions of importance to CS/SE, and expectation. Simulation of random variables and Monte Carlo methods. Central limit theorem. Basic statistical inference, parameter estimation, hypothesis testing, and linear regression. Introduction to stochastic processes. Illustrative examples and simulation exercises from queuing, reliability, and other CS/SE applications.",
                            Name = "Probability and Statistics in Computer Science and Software Engineering",
                            Number = 3341,
                            Prefix = "CS"
                        },
                        new
                        {
                            CourseId = 28,
                            ClassLevel = "UnderGraduate",
                            CourseType = 2,
                            Credits = 3,
                            Description = "Analysis of algorithms including time complexity and Big-O notation. Analysis of stacks, queues, and trees, including B-trees. Heaps, hashing, and advanced sorting techniques. Disjoint sets and graphs. Course emphasizes design and implementation.",
                            Name = "Data Structures and Introduction to Algorithmic Analysis",
                            Number = 3345,
                            Prefix = "CS"
                        },
                        new
                        {
                            CourseId = 29,
                            ClassLevel = "UnderGraduate",
                            CourseType = 2,
                            Credits = 3,
                            Description = "Introduction to software life cycle models. Software requirements engineering, formal specification and validation. Techniques for software design and testing. Cost estimation models. Issues in software quality assurance and software maintenance.",
                            Name = "Software Engineering",
                            Number = 3354,
                            Prefix = "CS"
                        },
                        new
                        {
                            CourseId = 30,
                            ClassLevel = "UnderGraduate",
                            CourseType = 2,
                            Credits = 3,
                            Description = "",
                            Name = "C/C++ Programming in a UNIX Environment",
                            Number = 3377,
                            Prefix = "CS"
                        },
                        new
                        {
                            CourseId = 31,
                            ClassLevel = "UnderGraduate",
                            CourseType = 2,
                            Credits = 3,
                            Description = "This course exposes students to major theoretical approaches and professional codes of ethics and how they may be applied to explore a range of important social issues in the information age. Issues of professional ethics, computer crime and privacy, intellectual property, the balance between the acceptability of risk and constraints such as cost, scheduling, safety and quality, the role of globalization and various important constitutional issues are explored by drawing upon case studies.",
                            Name = "Social Issues and Ethics in Science and Technology",
                            Number = 2361,
                            Prefix = "ECS"
                        },
                        new
                        {
                            CourseId = 32,
                            ClassLevel = "UnderGraduate",
                            CourseType = 2,
                            Credits = 1,
                            Description = "The purpose of this laboratory is to give students an intuitive understanding of digital circuits and systems. Laboratory exercises include construction of simple digital logic circuits using prototyping kits and board-level assembly of a personal computer.",
                            Name = "Digital Systems Laboratory",
                            Number = 4141,
                            Prefix = "CS"
                        },
                        new
                        {
                            CourseId = 33,
                            ClassLevel = "UnderGraduate",
                            CourseType = 2,
                            Credits = 3,
                            Description = "Principles of design and implementation of contemporary programming languages. Formal description including specification of syntax and semantics of programming languages. Language definition structures including binding, scoping, data types, control structures, parameter passing, abstraction mechanism, and run-time considerations. Design issues of imperative languages, object-oriented languages, functional languages and logic languages. Design, implement, and debug programs in various programming language paradigms.",
                            Name = "Organization of Programming Languages",
                            Number = 4337,
                            Prefix = "CS"
                        },
                        new
                        {
                            CourseId = 34,
                            ClassLevel = "UnderGraduate",
                            CourseType = 2,
                            Credits = 3,
                            Description = "Boolean algebra and logic circuits; synchronous sequential circuits; gate level design of ALSU, registers, and memory unit; register transfer operations; design of data path and control unit for a small computer; Input-Output interface.",
                            Name = " Digital Logic and Computer Design",
                            Number = 4341,
                            Prefix = "CS"
                        },
                        new
                        {
                            CourseId = 35,
                            ClassLevel = "UnderGraduate",
                            CourseType = 2,
                            Credits = 3,
                            Description = "This course emphasizes the concepts and structures necessary for the design and implementation of database management systems. Topics include data models, data normalization, data description languages, query facilities, file organization, index organization, file security, data integrity, and reliability.",
                            Name = "Database Systems",
                            Number = 4347,
                            Prefix = "CS"
                        },
                        new
                        {
                            CourseId = 36,
                            ClassLevel = "UnderGraduate",
                            CourseType = 2,
                            Credits = 3,
                            Description = "An introduction to fundamental concepts in operating systems: their design, implementation, and usage. Topics include process management, main memory management, virtual memory, I/O and device drivers, file systems, secondary storage management, and an introduction to critical sections and deadlocks.",
                            Name = "Operating Systems Concepts",
                            Number = 4348,
                            Prefix = "CS"
                        },
                        new
                        {
                            CourseId = 37,
                            ClassLevel = "UnderGraduate",
                            CourseType = 2,
                            Credits = 3,
                            Description = "Asymptomatic analysis, recurrences, and graph algorithms. Algorithm design techniques such as greedy method, dynamic programming, and divide-and-conquer. Issues from computational complexity. Course emphasizes a theoretical approach. ",
                            Name = "Advanced Algorithm Design and Analysis",
                            Number = 4349,
                            Prefix = "CS"
                        },
                        new
                        {
                            CourseId = 38,
                            ClassLevel = "UnderGraduate",
                            CourseType = 2,
                            Credits = 3,
                            Description = " A review of the abstract notions encountered in machine computation. Topics include finite automata, regular expressions, PDAs, and context-free languages.",
                            Name = "Automata Theory",
                            Number = 4384,
                            Prefix = "CS"
                        },
                        new
                        {
                            CourseId = 39,
                            ClassLevel = "UnderGraduate",
                            CourseType = 2,
                            Credits = 3,
                            Description = "This course is intended to complement theory and to provide an in-depth, hands-on experience in all aspects of a software development project. Students will work in teams on projects of interest to industry and will be involved in specifying the problem and its solution, designing and analyzing the solution, developing the software architecture, along with implementation and testing plans. The deliverables will include reports that document these steps as well as a final project report, including the challenges they faced, and a user manual of the developed system. Students will explore security issues of their project and its potential impact on society. Teams will also make presentations as well as demonstrate their software. Additionally, this course will cover topics related to computer science profession including ethics and professional responsibility, entrepreneurship, leadership, and project management.",
                            Name = "Computer Science Project",
                            Number = 4485,
                            Prefix = "CS"
                        },
                        new
                        {
                            CourseId = 40,
                            ClassLevel = "UnderGraduate",
                            CourseType = 3,
                            Credits = 3,
                            Description = "CS guided electives are 4000 level CS courses approved by the student's CS advisor. The following courses may be used as guided electives without the explicit approval of an advisor:",
                            Name = "Major Guided Elective I",
                            Number = 0,
                            Prefix = "CS"
                        },
                        new
                        {
                            CourseId = 41,
                            ClassLevel = "UnderGraduate",
                            CourseType = 3,
                            Credits = 3,
                            Description = "CS guided electives are 4000 level CS courses approved by the student's CS advisor. The following courses may be used as guided electives without the explicit approval of an advisor:",
                            Name = "Major Guided Elective II",
                            Number = 0,
                            Prefix = "CS"
                        },
                        new
                        {
                            CourseId = 42,
                            ClassLevel = "UnderGraduate",
                            CourseType = 3,
                            Credits = 3,
                            Description = "CS guided electives are 4000 level CS courses approved by the student's CS advisor. The following courses may be used as guided electives without the explicit approval of an advisor:",
                            Name = "Major Guided Elective III",
                            Number = 0,
                            Prefix = "CS"
                        },
                        new
                        {
                            CourseId = 43,
                            ClassLevel = "UnderGraduate",
                            CourseType = 4,
                            Credits = 3,
                            Description = "Both lower- and upper-division courses may count as free electives",
                            Name = "Free Elective I",
                            Number = 0,
                            Prefix = ""
                        },
                        new
                        {
                            CourseId = 44,
                            ClassLevel = "UnderGraduate",
                            CourseType = 4,
                            Credits = 3,
                            Description = "Both lower- and upper-division courses may count as free electives",
                            Name = "Free Elective II",
                            Number = 0,
                            Prefix = ""
                        },
                        new
                        {
                            CourseId = 45,
                            ClassLevel = "UnderGraduate",
                            CourseType = 4,
                            Credits = 3,
                            Description = "Both lower- and upper-division courses may count as free electives",
                            Name = "Free Elective III",
                            Number = 0,
                            Prefix = ""
                        },
                        new
                        {
                            CourseId = 46,
                            ClassLevel = "UnderGraduate",
                            CourseType = 4,
                            Credits = 2,
                            Description = "Both lower- and upper-division courses may count as free electives",
                            Name = "Free Elective I",
                            Number = 0,
                            Prefix = ""
                        });
                });

            modelBuilder.Entity("SchedulePicker.Models.Major", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("School")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Majors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Computer Science",
                            School = "Erik School of Engineering"
                        });
                });

            modelBuilder.Entity("SchedulePicker.Models.MajorCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("MajorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("MajorId");

                    b.ToTable("MajorCourses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 4,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 5,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 6,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 7,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 9,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 10,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 11,
                            CourseId = 11,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 12,
                            CourseId = 12,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 13,
                            CourseId = 13,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 14,
                            CourseId = 14,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 15,
                            CourseId = 15,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 16,
                            CourseId = 16,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 17,
                            CourseId = 17,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 18,
                            CourseId = 18,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 19,
                            CourseId = 19,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 20,
                            CourseId = 20,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 21,
                            CourseId = 21,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 22,
                            CourseId = 22,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 23,
                            CourseId = 23,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 24,
                            CourseId = 24,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 25,
                            CourseId = 25,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 26,
                            CourseId = 26,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 27,
                            CourseId = 27,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 28,
                            CourseId = 28,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 29,
                            CourseId = 29,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 30,
                            CourseId = 30,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 31,
                            CourseId = 31,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 32,
                            CourseId = 32,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 33,
                            CourseId = 33,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 34,
                            CourseId = 34,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 35,
                            CourseId = 35,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 36,
                            CourseId = 36,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 37,
                            CourseId = 37,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 38,
                            CourseId = 38,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 39,
                            CourseId = 39,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 40,
                            CourseId = 40,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 41,
                            CourseId = 41,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 42,
                            CourseId = 42,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 43,
                            CourseId = 43,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 44,
                            CourseId = 44,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 45,
                            CourseId = 45,
                            MajorId = 1
                        },
                        new
                        {
                            Id = 46,
                            CourseId = 46,
                            MajorId = 1
                        });
                });

            modelBuilder.Entity("SchedulePicker.Models.PreReq", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("PrerequisiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("PrerequisiteId");

                    b.ToTable("PreReqs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 2,
                            PrerequisiteId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 14,
                            PrerequisiteId = 3
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 5,
                            PrerequisiteId = 4
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 12,
                            PrerequisiteId = 11
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 10,
                            PrerequisiteId = 9
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 4,
                            PrerequisiteId = 3
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 5,
                            PrerequisiteId = 14
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 21,
                            PrerequisiteId = 19
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 22,
                            PrerequisiteId = 3
                        });
                });

            modelBuilder.Entity("SchedulePicker.Models.StudentCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentCourse");
                });

            modelBuilder.Entity("Schedule.Models.Student", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.Student");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.ToTable("Students");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.StudentClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.Student", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.StudentLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.Student", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.StudentRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.Student", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.StudentToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.Student", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchedulePicker.Models.CoReq", b =>
                {
                    b.HasOne("SchedulePicker.Models.Course", "Corequisite")
                        .WithMany()
                        .HasForeignKey("CorequisiteId");

                    b.HasOne("SchedulePicker.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId");
                });

            modelBuilder.Entity("SchedulePicker.Models.MajorCourse", b =>
                {
                    b.HasOne("SchedulePicker.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedulePicker.Models.Major", "Major")
                        .WithMany()
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchedulePicker.Models.PreReq", b =>
                {
                    b.HasOne("SchedulePicker.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId");

                    b.HasOne("SchedulePicker.Models.Course", "Prerequisite")
                        .WithMany()
                        .HasForeignKey("PrerequisiteId");
                });

            modelBuilder.Entity("SchedulePicker.Models.StudentCourse", b =>
                {
                    b.HasOne("SchedulePicker.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId");

                    b.HasOne("Schedule.Models.Student", "Student")
                        .WithMany("Courses")
                        .HasForeignKey("StudentId");
                });
#pragma warning restore 612, 618
        }
    }
}
